services:
  db:
    image: postgis/postgis:16-3.5
    container_name: bdd
    restart: unless-stopped
    environment:
      POSTGRES_DB: route
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  API:
    image: node:20-alpine
    container_name: API
    working_dir: /app
    volumes:
      - ./API:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: route
      DB_USER: admin
      DB_PASSWORD: admin
      TILE_SERVER_URL: http://tileserver:8080
    depends_on:
      - db

  # ============================================
  # SERVEUR DE TUILES OFFLINE - Antananarivo
  # Utilise un proxy de cache pour tuiles OSM
  # ============================================
  
  tileserver:
    build:
      context: ./tiles
      dockerfile: Dockerfile
    container_name: tileserver
    restart: unless-stopped
    volumes:
      - tiles-cache:/app/cache
    ports:
      - "3001:8080"
    environment:
      - CACHE_DIR=/app/cache
      - DEFAULT_CENTER_LAT=-18.8792
      - DEFAULT_CENTER_LON=47.5079
      - DEFAULT_ZOOM=12

  # mobile:
  #   image: node:22-alpine
  #   container_name: mobile
  #   working_dir: /app
  #   volumes:
  #     - ./mobile:/app
  #     - /app/node_modules
  #   command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     VITE_API_URL: http://API:3000
  #   depends_on:
  #     - API

  # # web:
  #   image: node:20-alpine
  #   container_name: web
  #   working_dir: /app
  #   volumes:
  #     - ./web:/app
  #     - /app/node_modules
  #   command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
  #   ports:
  #     - "5002:5173"
  #   environment:
  #     VITE_API_URL: http://API:3000
  #   depends_on:
  #     - API

volumes:
  pgdata:
  tiles-cache:
