services:
  db:
    image: postgis/postgis:16-3.5
    container_name: bdd
    restart: unless-stopped
    environment:
      POSTGRES_DB: route
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  API:
    image: node:20-alpine
    container_name: API
    working_dir: /app
    volumes:
      - ./API:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: route
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - db

  mobile:
    image: node:22-alpine
    container_name: mobile
    working_dir: /app
    volumes:
      - ./mobile:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5001:5001"
    environment:
      VITE_API_URL: http://API:3000
    depends_on:
      - API

  web:
    image: node:20-alpine
    container_name: web
    working_dir: /app
    volumes:
      - ./web:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5002:5173"
    environment:
      VITE_API_URL: http://API:3000
    depends_on:
      - API

  tiles-init:
    image: alpine:latest
    container_name: tiles-init
    restart: "no"
    volumes:
      - ./tiles:/data
      - ./init-tiles.sh:/init-tiles.sh
    entrypoint: sh /init-tiles.sh
    networks:
      - default

  tileserver:
    image: maptiler/tileserver-gl
    container_name: tileserver
    restart: unless-stopped
    volumes:
      - ./tiles:/data
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    depends_on:
      tiles-init:
        condition: service_completed_successfully

volumes:
  pgdata:
